# Generated by Django 4.2.23 on 2025-07-07 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('NO_APLICA', 'No Aplica')], default='ABIERTO', max_length=50)),
                ('descripcion_problema', models.TextField()),
                ('nivel_critico', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=50)),
                ('tipo_problema', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('area_asignada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_en_area', to='core.area')),
                ('cliente_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.cliente')),
                ('trabajador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('trabajador_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='miembros', to='core.area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion_texto', models.TextField()),
                ('fecha_hora_observacion', models.DateTimeField(auto_now_add=True)),
                ('autor_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ticket_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Jefatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_jefatura', models.DateField()),
                ('fecha_fin_jefatura', models.DateField(blank=True, help_text='Dejar en blanco si la jefatura está activa.', null=True)),
                ('area_jefatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
                ('departamento_jefatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
                ('trabajador_jefe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_jefatura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derivacion', models.DateTimeField(auto_now_add=True)),
                ('motivo_derivacion', models.TextField()),
                ('area_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_entrantes', to='core.area')),
                ('area_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_salientes', to='core.area')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='core.ticket')),
                ('trabajador_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
